apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-app
  template:
    metadata:
      labels:
        app: sre-app
    spec:
      containers:
        - name: sre-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: DATABASE_URL
              value: "{{ .Values.env.DATABASE_URL }}"
            - name: PHX_HOST
              value: "{{ .Values.env.PHX_HOST }}"
            - name: SECRET_KEY_BASE
              value: "{{ .Values.env.SECRET_KEY_BASE }}"
          command: ["/bin/sh"]
          args: ["-c", "migrate && server"]
          livenessProbe:
            httpGet:
              path: /_health
              port: 4000
          readinessProbe:
            httpGet:
              path: /_health
              port: 4000
