{{ if .Values.gcp.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stord-ingress
  annotations:
    networking.gke.io/managed-certificates: stord-cert
spec:
  rules:
    - host: stord.bauerworld.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sre-app-sre-technical-challenge
                port:
                  number: 80
{{ end }}
